Refactor
alanluqman/OOP-school-library pull request #5
Opened 2022-10-03 13:51 UTC by principlebrothers

## Description
In this pull request my partner @alanluqman  and I @principlebrothers  refactored the `main.rb` and implemented 
- SOLID
- DRY
- YAGNI principles

### Requires
- Make sure that the role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).
- Extract some pieces of logic into separate class(es).

2022-10-03 14:35 UTC, phelian23 requested changes
Hi @Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
No linters errors ✔️
Descriptive pull request ✔️
Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 14:35 UTC, phelian23 commented on old_main.md
> +
- [ ] Kindly remove all commented code. Remember you can always use git commit history to check previous (old) code.

2022-10-03 14:35 UTC, phelian23 commented on app.rb
>      end
- [x] Kindly refactor the this file by putting all requests for input and input validation in the startup.rb file that is dedicated for that purpose in your case. 
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L52-L60
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L66-L73
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L91-L103
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L105-L116
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L119-L123
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L135-L138
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L152-L153
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L152-L153

- [x] Also, the lines to create a new student/teacher should have been included in the create person method. 
https://github.com/alanluqman/OOP-school-library/blob/1ead0a7cd235c075927134f9333a742cb73d3ed3/app.rb#L78-L88

2022-10-03 15:46 UTC, alanluqman commented
Thanks, @phelian23, for the review to make us keep the code clean.  We have removed `old_main.md` file.
There are few things you request us to change that is contrary to the requirements from the previous project instruction. 
1. the methods you want us to move to the startup file is meant to be in the app.rb file.
2. we are told to review the main.rb file instead for today's work, not the app.rb

2022-10-03 16:29 UTC, FrederickMih requested changes
Hi @principlebrothers, @alanluqman 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)


 ## Highlights

- PR has a good title and summary :heavy_check_mark: 
- Correct Git flow :+1: 
- No linter error :+1: 

 ## Required Changes ♻️

- [ ] Hi team, as requested by the previous reviewer, we need to make sure that we respect the Single responsibility rules of SOLID. Single-responsibility Principle (SRP) states that: **A class should have only one job** Right now your app class is requesting inputs from the user and also performing validations. I'll kindly advise you to create other classes/methods in another file for these aspects. Hence you must not move all these methods to the startup file, you can create another for this perspective. No input from the user or validations should be done in your app file. This way, your work will be cleaner and neater.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 09:52 UTC, omarsalem7 approved these changes
Hi Team 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 10:29 UTC, principlebrothers commented
@alanluqman  and @principlebrothers  appreciate the taken to review our work. Thank your @FrederickMih

2022-10-04 12:46 UTC, merged